version: '3.8'

services:
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: fridge
    ports:
      - 5432:5432
