   name: Spring Boot Docker Tests

   on:
     push:
       branches: [ main ]

   jobs:
     build-and-test:
       runs-on: ubuntu-latest

       steps:
       - uses: actions/checkout@v2
       - name: Set up JDK 17
         uses: actions/setup-java@v2
         with:
           distribution: 'adopt'
           java-version: '17'

       - name: Build with Maven
         working-directory: ./RaspbrrryFridge backend
         run: ./mvnw package -DskipTests

       - name: Build Docker Image
         working-directory: ./RaspbrrryFridge backend
         run: docker build -t springboot-app:latest .

       - name: Run Tests
         working-directory: ./RaspbrrryFridge backend
         run: ./mvnw test
